import dotenv from 'dotenv';
dotenv.config();
import { prisma } from '../src/lib/prisma';

// const prisma = new PrismaClient(); // Removed

async function main() {
    console.log('🔍 Checking latest notifications...');
    const count = await prisma.notification.count();
    console.log(`Total notifications in DB: ${count}`);

    const last5 = await prisma.notification.findMany({
        take: 5,
        orderBy: { createdAt: 'desc' }
    });

    console.log('Last 5 notifications:');
    console.log(JSON.stringify(last5, null, 2));

    // Check "Start of Day" logic
    const { DateTime } = require('luxon');
    const startOfToday = DateTime.now().startOf('day').toJSDate();
    console.log(`\n📅 Server "Start of Today" (Luxon): ${startOfToday.toISOString()}`);

    const filtered = await prisma.notification.findMany({
        where: { createdAt: { gte: startOfToday } }
    });
    console.log(`Notifications found with "Today" filter: ${filtered.length}`);

    // DEBUG: Check appointments for test patient
    const TEST_PHONE = '595981123456';
    const patient = await prisma.patient.findFirst({ where: { phone: { contains: TEST_PHONE } } });
    if (patient) {
        console.log(`\n👤 Found Test Patient: ${patient.id} (${patient.firstName})`);
        const appts = await prisma.appointment.findMany({
            where: { patientId: patient.id }
        });
        console.log(`Appointments for patient: ${appts.length}`);
        appts.forEach(a => console.log(` - ID: ${a.id} | Date: ${a.date} | Status: ${a.status}`));
    } else {
        console.log('\n❌ Test patient not found in DB check');
    }

    // DEBUG: Try creating a notification manually to verify table works
    try {
        console.log('\n🛠 Attempting to create a manual notification...');
        const notif = await prisma.notification.create({
            data: {
                type: 'info',
                title: 'Manual Debug Test',
                message: 'This is a test notification generated by debug script.',
                read: false,
                createdAt: new Date()
            }
        });
        console.log(`✅ Manual notification created! ID: ${notif.id}`);
    } catch (e: any) {
        console.error('❌ Failed to create manual notification:', e);
    }

    // DEBUG: Trigger Webhook to verify complete flow
    console.log('\n📡 Triggering Webhook for Confirmation...');
    const axios = require('axios');
    try {
        await axios.post('http://localhost:3000/api/webhooks/twilio/incoming', {
            From: `whatsapp:+${TEST_PHONE}`,
            Body: '',
            ButtonPayload: 'confirm_yes'
        });
        console.log('✅ Webhook sent. Waiting for processing...');
        await new Promise(r => setTimeout(r, 2000));

        // Check if notification exists
        const countAfter = await prisma.notification.count({
            where: {
                createdAt: { gte: startOfToday },
                title: 'Cita Confirmada'
            }
        });
        console.log(`\n🔔 Notifications count after webhook: ${countAfter}`);
        if (countAfter > 0) {
            console.log('🎉 SUCCESS: Notification created by webhook!');
        } else {
            console.log('⚠️ FAILURE: Webhook processed but NO notification created.');
        }

    } catch (e: any) {
        console.error('❌ Webhook trigger failed:', e.message);
    }
}

main()
    .catch(e => console.error(e))
    .finally(async () => await prisma.$disconnect());
